const uniqueCodes = {
	reqOriginRequired: {
		responseCode: 512,
		code: 'REQ_ORIGIN_REQUIRED',
		status: 403,
		message: 'Request origin is required',
	},
	reqOriginInvalid: {
		responseCode: 520,
		code: 'REQ_ORIGIN_INVALID',
		status: 403,
		message: 'Request origin is invalid',
	},
	reqOriginExpired: {
		responseCode: 528,
		code: 'REQ_ORIGIN_EXPIRED',
		status: 403,
		message: 'Request origin is expired',
	},
	appTypeNotValid: {
		responseCode: 536,
		code: 'APP_TYPE_NOT_VALID',
		status: 403,
		message: 'App type is not valid',
	},
	appTypeRequired: {
		responseCode: 544,
		code: 'APP_TYPE_REQUIRED',
		status: 403,
		message: 'App type is required',
	},
	appTypeValid: {
		responseCode: 552,
		code: 'APP_TYPE_VALID',
		status: 200,
		message: 'App type is valid',
	},
	emailRequired: {
		responseCode: 560,
		code: 'EMAIL_REQUIRED',
		status: 400,
		message: 'Email is required',
	},
	emailNotValid: {
		responseCode: 568,
		code: 'EMAIL_NOT_VALID',
		status: 400,
		message: 'Email is not valid',
	},
	emailValid: {
		responseCode: 576,
		code: 'EMAIL_VALID',
		status: 200,
		message: 'Email is valid',
	},
	internalServerError: {
		responseCode: 584,
		code: 'INTERNAL_SERVER_ERROR',
		status: 500,
		message: 'Internal server error',
	},
	campusDomainRequired: {
		responseCode: 592,
		code: 'CAMPUS_DOMAIN_REQUIRED',
		status: 400,
		message: 'Campus email domain is required',
	},
	campusNotFound: {
		responseCode: 600,
		code: 'CAMPUS_NOT_FOUND',
		status: 404,
		message: 'Campus not found',
	},
	campusFound: {
		responseCode: 608,
		code: 'CAMPUS_FOUND',
		status: 200,
		message: 'Campus found',
	},
	emailOrUserIdRequired: {
		responseCode: 616,
		code: 'EMAIL_OR_USER_ID_REQUIRED',
		status: 400,
		message: 'Email or user id is required',
	},
	userNotFound: {
		responseCode: 624,
		code: 'USER_NOT_FOUND',
		status: 404,
		message: 'User not found',
	},
	userFound: {
		responseCode: 632,
		code: 'USER_FOUND',
		status: 200,
		message: 'User found',
	},
	userFullNameRequired: {
		responseCode: 640,
		code: 'USER_FULL_NAME_REQUIRED',
		status: 400,
		message: 'User full name is required',
	},
	userCreated: {
		responseCode: 648,
		code: 'USER_CREATED',
		status: 200,
		message: 'User created',
	},
	unauthorized: {
		responseCode: 656,
		code: 'UNAUTHORIZED',
		status: 401,
		message: 'Token unauthorized',
	},
	invalidUserId: {
		responseCode: 664,
		code: 'INVALID_USER_ID',
		status: 400,
		message: 'Invalid user id',
	},
	invalidItemId: {
		responseCode: 672,
		code: 'INVALID_ITEM_ID',
		status: 400,
		message: 'Invalid item id',
	},
	itemNotAvailable: {
		responseCode: 680,
		code: 'ITEM_NOT_AVAILABLE',
		status: 404,
		message: 'Item not available',
	},
	itemAvailable: {
		responseCode: 688,
		code: 'ITEM_AVAILABLE',
		status: 200,
		message: 'Item available',
	},
	unprocessable: {
		responseCode: 696,
		code: 'UNPROCESSABLE',
		status: 422,
		message: 'Request unprocessable',
	},
	userNotCreated: {
		responseCode: 704,
		code: 'USER_NOT_CREATED',
		status: 400,
		message: 'User not created',
	},
	invalidCart: {
		responseCode: 712,
		code: 'INVALID_CART',
		status: 400,
		message: 'Invalid cart',
	},
	invalidOutletId: {
		responseCode: 720,
		code: 'INVALID_OUTLET_ID',
		status: 400,
		message: 'Invalid outlet id',
	},
	invalidQuantity: {
		responseCode: 728,
		code: 'INVALID_QUANTITY',
		status: 400,
		message: 'Invalid quantity',
	},
	cartNotUpdated: {
		responseCode: 736,
		code: 'CART_NOT_UPDATED',
		status: 400,
		message: 'Cart not updated',
	},
	cartUpdated: {
		responseCode: 744,
		code: 'CART_UPDATED',
		status: 200,
		message: 'Cart updated',
	},
	itemAddedToCart: {
		responseCode: 752,
		code: 'ITEM_ADDED_TO_CART',
		status: 200,
		message: 'Item added to cart',
	},
	itemRemovedFromCart: {
		responseCode: 760,
		code: 'ITEM_REMOVED_FROM_CART',
		status: 200,
		message: 'Item removed from cart',
	},
	cartCleared: {
		responseCode: 768,
		code: 'CART_CLEARED',
		status: 200,
		message: 'Cart cleared',
	},
	invalidCampusId: {
		responseCode: 776,
		code: 'INVALID_CAMPUS_ID',
		status: 400,
		message: 'Invalid campus id',
	},
	noOutletsFound: {
		responseCode: 784,
		code: 'NO_OUTLETS_FOUND',
		status: 404,
		message: 'No outlets found',
	},
	outletsFound: {
		responseCode: 792,
		code: 'OUTLETS_FOUND',
		status: 200,
		message: 'Outlets found',
	},
	noItemsFound: {
		responseCode: 800,
		code: 'NO_ITEMS_FOUND',
		status: 404,
		message: 'No items found',
	},
	itemsFound: {
		responseCode: 808,
		code: 'ITEMS_FOUND',
		status: 200,
		message: 'Items found',
	},
	noOutletFound: {
		responseCode: 816,
		code: 'NO_OUTLET_FOUND',
		status: 404,
		message: 'No outlet found',
	},
	outletFound: {
		responseCode: 824,
		code: 'OUTLET_FOUND',
		status: 200,
		message: 'Outlet found',
	},
	avgZingTimeCalculated: {
		responseCode: 832,
		code: 'AVG_ZING_TIME_CALCULATED',
		status: 200,
		message: 'Average zing time calculated',
	},
	noOrdersFound: {
		responseCode: 840,
		code: 'NO_ORDERS_FOUND',
		status: 404,
		message: 'No orders found',
	},
	invalidSetMode: {
		responseCode: 848,
		code: 'INVALID_SET_MODE',
		status: 400,
		message: 'Invalid set mode',
	},
	outletAvailabilitySet: {
		responseCode: 856,
		code: 'OUTLET_AVAILABILITY_SET',
		status: 200,
		message: 'Outlet availability set',
	},
	outletNotActive: {
		responseCode: 864,
		code: 'OUTLET_NOT_ACTIVE',
		status: 400,
		message: 'Outlet is not active',
	},
	itemAvailabilitySet: {
		responseCode: 872,
		code: 'ITEM_AVAILABILITY_SET',
		status: 200,
		message: 'Item availability set',
	},
};

export default uniqueCodes;
